[package]
name = "gallagher-rfid-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
gallagher-rfid-pcsc = { path = "../gallagher-rfid-pcsc" }
gallagher-rfid-core = { path = "../gallagher-rfid-core" }
